# Generated by Django 3.1.3 on 2022-02-18 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stuNo', models.IntegerField()),
                ('stuName', models.CharField(max_length=100)),
                ('stuId', models.IntegerField()),
                ('stuAddress', models.CharField(max_length=100)),
            ],
        ),
    ]
